site:
  title: "Benjamin Wunn"
  baseline: "Your content driven static site generator."
  #canonicalurl:
  baseurl: http://bw.github.io
  description: "Cecil is a CLI application that merges plain text files (written in Markdown), images and Twig templates to generate a static website."
  language: de
  languages:
    de:
      name: German
      locale: de_DE
  author:
    name: Benjamin Wunn
    url: http://bw.github.io
